name: Mirroring
on:
  push:
  pull_request:

jobs:
  push_to_mirror:
    name: Push to Mirror
    runs-on: self-hosted
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Git Repository
        run: |
          git status
          ls -la /github/workspace

      - name: Test SSH Connection
        run: |
          ssh -T git@github.com

      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        working-directory: /github/workspace
