name: Mirroring
on:
  push:
  pull_request:


jobs:
  push_to_mirror:
    name: Push to Mirror
    runs-on: self-hosted
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Git Repository
        run: |
          echo "Current directory:"
      - name: Debug Git Repository
        working-directory: ${{ github.workspace }}
        run: |
          echo "Listing files in workspace:"
          ls -la ${{ github.workspace }}  # Use GitHub workspace path
          echo "Git status:"
          git status

      - name: Test SSH Connection
        run: |
          ssh -T git@github.com || true

      - name: Check if workspace exists
        working-directory: ${{ github.workspace }}
        run: |
          if [ -d ${{ github.workspace }} ]; then
            echo "Workspace exists at ${{ github.workspace }}"
          else
              echo "Workspace does not exist at ${{ github.workspace }}"
          fi

      - name: Push to Mirror
        run: |
          cd /github/workspace
          git status  # Just to ensure we're in the right place
          git push ${{ vars.MIRROR_URL }} # Or whatever your mirroring command is
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

