name: Mirroring
run-name: mirroring

on:
    push:
    pull_request:

jobs:
    push_to_mirror:
        name: Push to Mirror
        runs-on: ubuntu
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - uses: pixta-dev/repository-mirroring-action@v1
            with:
              target_repo_url: ${{ vars.MIRROR_URL }}
              ssh_private_key: # <-- use 'secrets' to pass credential information.
                ${{ secrets.GIT_SSH_PRIVATE_KEY }}


