name: Mirroring
on:
  push:
  pull_request:


jobs:
  push_to_mirror:
    name: Push to Mirror
    runs-on: self-hosted
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Git Repository
        run: |
          echo "Current directory:"
      - name: Debug Git Repository
        working-directory: ${{ github.workspace }}
        run: |
          echo "Listing files in workspace:"
          ls -la ${{ github.workspace }}  # Use GitHub workspace path
          echo "Git status:"
          git status

      # - name: Test SSH Connection
      #   run: |
      #     ssh -T git@github.com

      # - name: Check if workspace exists
      #   working-directory: ${{ github.workspace }}
      #   run: |
      #       echo "Workspace exists at ${{ github.workspace }}"
      #       else
      #         echo "Workspace does not exist at ${{ github.workspace }}"
      #       fi

      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
