name: Mirroring
on:
  push:
  pull_request:

defaults:
  run:
    working-directory: /github/workspace

jobs:
  push_to_mirror:
    name: Push to Mirror
    runs-on: self-hosted
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Git Repository
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files in /github/workspace:"
          ls -la /github/workspace
          echo "Git status:"
          git status

      - name: Test SSH Connection
        run: |
          ssh -T git@github.com

      - name: Check if /github/workspace exists
        run: |
          if [ -d /github/workspace ]; then
            echo "/github/workspace exists"
          else
            echo "/github/workspace does not exist"
          fi

      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
