name: Updating
run-name: updating-main-dev-branches

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

permissions:
    contents: write

jobs:
    update_dev_branches:
        name: Update Main Dev Branches
        runs-on: self-hosted
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                    fetch-depth: 0

            - name: Update Main Dev Branches
              run: |
                git switch backend && git pull origin dev && git push || echo "No changes or the branch does not exist"
                git switch frontend && git pull origin dev && git push || echo "No changes or the branch does not exist"
                git switch mobile && git pull origin dev && git push || echo "No changes or the branch does not exist"
                git switch devops && git pull origin dev && git push || echo "No changes or the branch does not exist"
                git switch documentation && git pull origin dev && git push || echo "No changes or the branch does not exist"
